# -*- coding: utf-8 -*-
"""Енот на золотом троне.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MsWimkj04IQrdNVmZcg8BNZy7BXZMbgW
"""

#енот на золотом троне
import matplotlib.pyplot as plt
import numpy as np

from mpl_toolkits.mplot3d import Axes3D

x, y, z = np.indices((20, 20, 20+15))
#разметка карты
transparent_cubes = (x < 20) & (y < 20) & (z < 20)
opaque_cubes_3 = ( x <= 20) & (y <= 20) & (z == 0)

#tron
opaque_cubes_1 = ( x <= 19) & (y >= 0) & (y <= 19) & (z <= 5)
opaque_cubes_2 = ( x <= 19) & (y >= 0 ) & (y<=4) & (z >= 6) & (z<=6+5)
opaque_cubes_4 = ( x <= 19) & (y >= 15 ) & (y<=19) & (z >= 6) & (z<=6+5)
opaque_cubes_5 = (x<=4) & ( x >= 0) & (y >= 0 ) & (y<=19) & (z >= 6) & (z<=6+5+9)
opaque_cubes_6 = (x<=4) & ( x >= 0) & (y >= 5 ) & (y<=15) & (z >= 6) & (z<=6+5+9+4)
opaque_cubes_7 = (x<=4) & ( x >= 0) & (y >= 7 ) & (y<=13) & (z >= 6) & (z<=6+5+9+4+4)
opaque_cubes_8 = (x<=3) & ( x >= 1) & (y >= 8 ) & (y<=12) & (z > 6+5+9+4+4) & (z<=6+5+9+4+4+2)
opaque_cubes_9 = (x<=2) & ( x >= 2) & (y >= 9 ) & (y<=11) & (z > 6+5+9+4+4+1) & (z<=6+5+9+4+4+2+1)
opaque_cubes_10 = (x<=2) & ( x >= 2) & (y >= 10 ) & (y<=10) & (z > 6+5+9+4+4+1+2) & (z<=6+5+9+4+4+2+2)

#enot
opaque_cubes_11 = (x<=9) & ( x >= 5) & (y > 4 ) & (y<15) & (z >= 6) & (z<=29)
opaque_cubes_12 = (x<=11) & ( x >= 5) & (y > 4 ) & (y<15) & (z >= 22) & (z<=29)
opaque_cubes_13 = (x<=11) & ( x >= 5) & (y >= 2 ) & (y<5) & (z >= 23) & (z<=26)
opaque_cubes_14 = (x<=11) & ( x >= 5) & (y < 20-2 ) & (y>=20-5) & (z >= 23) & (z<=26)
opaque_cubes_15 = (x<=10) & ( x >= 10) & (y > 4 ) & (y<15) & (z >= 6) & (z<=21)

opaque_cubes_16 = (x<=17) & ( x >= 10) & (y >= 5 ) & (y<=7) & (z >= 7) & (z<=9)
opaque_cubes_17 = (x<=17) & ( x >= 10) & (y <= 20-6 ) & (y>=20-8) & (z >= 7) & (z<=9)
opaque_cubes_18 = (x<=20) & ( x > 17) & (y <= 20-6 ) & (y>=20-8) & (z >= 7) & (z<=9+2)
opaque_cubes_19 = (x<=20) & ( x > 17) & (y >= 5 ) & (y<=7) & (z >= 7) & (z<=9+2)

opaque_cubes_20 = (x<=17) & ( x >= 10) & (y >= 5 ) & (y<=7) & (z >= 17) & (z<=19)
opaque_cubes_21 = (x<=17) & ( x >= 10) & (y <= 20-6 ) & (y>=20-8) & (z >= 17) & (z<=19)
opaque_cubes_22 = (x<=20) & ( x > 17) & (y <= 20-6 ) & (y>=20-8) & (z >= 17) & (z<=19+2)
opaque_cubes_23 = (x<=20) & ( x > 17) & (y >= 5 ) & (y<=7) & (z >= 17) & (z<=19+2)

opaque_cubes_24 = (x<=5) & ( x >= 3) & (y >= 14 ) & (y<= 16) & (z >= 29) & (z<=32)
opaque_cubes_25 = (x<=5) & ( x >= 3) & (y <= 20-15 ) & (y>= 20-17) & (z >= 29) & (z<=32)

opaque_cubes_26 = (x<=11) & ( x >= 11) & (y<=6) & ( y >= 3) & (z >= 24) & (z<=26)
opaque_cubes_29 = (x<=11) & ( x >= 11) & (y>=20-7) & ( y <= 20-4) & (z >= 24) & (z<=26)
opaque_cubes_27 = (x<=11) & ( x >= 11) & (y<=14) & ( y >= 5) & (z >= 25) & (z<=27)
opaque_cubes_28 = (x<=11) & ( x >= 11) & (y<=12) & ( y >= 7) & (z >= 28) & (z<=28)
opaque_cubes_30 = (x<=11) & ( x >= 11) & (y<=14) & ( y >= 5) & (z >= 22) & (z<=23)
opaque_cubes_31 = (x<=11) & ( x >= 11) & (y<=12) & ( y >= 7) & (z >= 24) & (z<=24)

opaque_cubes_32 = (x<=15) & ( x >= 12) & (y<=11) & ( y >= 8) & (z >= 23) & (z<=24)
opaque_cubes_33 = (x<=15) & ( x >= 15) & (y<=10) & ( y >= 9) & (z >= 24) & (z<=24)

opaque_cubes_34 = (x<=11) & ( x >= 11) & (y<=8) & ( y >= 8) & (z >= 26) & (z<=27)
opaque_cubes_35 = (x<=11) & ( x >= 11) & (y>=19-8) & ( y <= 19-8) & (z >= 26) & (z<=27)

opaque_cubes_36 = (x<=11) & ( x >= 11) & (y<=8) & ( y >= 6) & (z >= 29) & (z<=29)
opaque_cubes_37 = (x<=11) & ( x >= 11) & (y>=19-8) & ( y <= 19-6) & (z >= 29) & (z<=29)
opaque_cubes_38 = (x<=11) & ( x >= 11) & (y<=6) & ( y >= 6) & (z >= 28) & (z<=28)
opaque_cubes_39 = (x<=11) & ( x >= 11) & (y>=19-6) & ( y <= 19-6) & (z >= 28) & (z<=28)


voxels1 = transparent_cubes
voxels2 = opaque_cubes_1 | opaque_cubes_2 | opaque_cubes_27 | opaque_cubes_30 | opaque_cubes_38 | opaque_cubes_39 | opaque_cubes_37 | opaque_cubes_36 | opaque_cubes_35 | opaque_cubes_34 | opaque_cubes_33 | opaque_cubes_31 | opaque_cubes_32 | opaque_cubes_28 | opaque_cubes_29 | opaque_cubes_25 | opaque_cubes_26 | opaque_cubes_24 | opaque_cubes_4 | opaque_cubes_20 | opaque_cubes_21 | opaque_cubes_22 | opaque_cubes_23 | opaque_cubes_5 | opaque_cubes_19 | opaque_cubes_18 | opaque_cubes_6 | opaque_cubes_17 | opaque_cubes_7 | opaque_cubes_15 | opaque_cubes_16 | opaque_cubes_8 | opaque_cubes_9 | opaque_cubes_10 | opaque_cubes_11 | opaque_cubes_12 | opaque_cubes_14 | opaque_cubes_13 | opaque_cubes_3

colors1 = np.empty(voxels1.shape, dtype=object)
colors1[transparent_cubes] = 'white'


colors2 = np.empty(voxels2.shape, dtype=object)
colors2[opaque_cubes_1] = 'yellow'
colors2[opaque_cubes_2] = 'yellow'
colors2[opaque_cubes_3] = 'white'
colors2[opaque_cubes_4] = 'yellow'
colors2[opaque_cubes_5] = 'yellow'
colors2[opaque_cubes_6] = 'yellow'
colors2[opaque_cubes_7] = 'yellow'
colors2[opaque_cubes_8] = 'white'
colors2[opaque_cubes_9] = 'white'
colors2[opaque_cubes_10] = 'black'
#enot
colors2[opaque_cubes_11] = 'grey'
colors2[opaque_cubes_12] = 'grey'
colors2[opaque_cubes_13] = 'white'
colors2[opaque_cubes_14] = 'white'
colors2[opaque_cubes_15] = 'white'
colors2[opaque_cubes_16] = 'grey'
colors2[opaque_cubes_17] = 'grey'
colors2[opaque_cubes_18] = 'black'
colors2[opaque_cubes_19] = 'black'
colors2[opaque_cubes_20] = 'grey'
colors2[opaque_cubes_21] = 'grey'
colors2[opaque_cubes_22] = 'black'
colors2[opaque_cubes_23] = 'black'
colors2[opaque_cubes_24] = 'grey'
colors2[opaque_cubes_25] = 'grey'
colors2[opaque_cubes_26] = 'black'
colors2[opaque_cubes_27] = 'black'
colors2[opaque_cubes_28] = 'black'
colors2[opaque_cubes_29] = 'black'
colors2[opaque_cubes_30] = 'white'
colors2[opaque_cubes_31] = 'white'
colors2[opaque_cubes_32] = 'white'
colors2[opaque_cubes_33] = 'black'
colors2[opaque_cubes_34] = 'white'
colors2[opaque_cubes_35] = 'white'
colors2[opaque_cubes_36] = 'white'
colors2[opaque_cubes_37] = 'white'
colors2[opaque_cubes_38] = 'white'
colors2[opaque_cubes_39] = 'white'



# and plot everything
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.voxels(voxels2, facecolors=colors2, edgecolor='none')
fig.set_figheight(16)
fig.set_figwidth(15)

plt.show()